version: '3.7'

volumes:
  kong_data: {}

networks:
  kong-net:
    external: false

services:

  kong:
    image: "${KONG_DOCKER_TAG:-kong:3.2.2-alpine}"
    user: "${KONG_USER:-kong}"
    environment:
      KONG_DECLARATIVE_CONFIG: /opt/conf/kong.yml
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: kong-mocking-advanced
      KONG_LOG_LEVEL: 'debug'
      #KONG_LUA_PACKAGE_PATH: '/usr/local/kong/kong-mocking-advanced;'
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    volumes:
      - .:/opt/conf
    command: sh /opt/conf/build.sh
